In [6]:
import numpy as np
import paddle
from paddle_quantum.circuit import UAnsatz

# 设置角度参数 theta = pi
theta = np.array([np.pi])
    
# 我们需要将 Numpy array 转换成 Paddle 中的 Tensor
theta = paddle.to_tensor(theta)

# 设置计算所需的量子比特数量
num_qubits = 1

# 初始化我们的单比特量子电路
cir = UAnsatz(num_qubits)

# 在第一个量子比特(第0号量子比特)的位置上施加一个 Rx 旋转门， 角度为 pi
which_qubit = 0
cir.rx(theta, which_qubit)

# 打印出这个量子门
# 转换成 numpy 
print('量子门的矩阵表达式为：')
print(cir.U.numpy())


量子门的矩阵表达式为：
[[ 6.123234e-17+0.j -6.123234e-17-1.j]
 [ 6.123234e-17-1.j  6.123234e-17+0.j]]
/usr/local/anaconda3/envs/paddle_quantum_env/lib/python3.7/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/anaconda3/envs/paddle_quantum_env/lib/python3.7/site-packages/paddle/fluid/framework.py:687: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  elif dtype == np.bool:
/usr/local/anaconda3/en

In [9]:
#y gate
import numpy as np
import paddle
from paddle_quantum.circuit import UAnsatz

# 设置角度参数 theta = pi
theta = np.array([np.pi])
    
# 我们需要将 Numpy array 转换成 Paddle 中的 Tensor
theta = paddle.to_tensor(theta)

# 设置计算所需的量子比特数量
num_qubits = 1

# 初始化我们的单比特量子电路
cir = UAnsatz(num_qubits)

# 在第一个量子比特(第0号量子比特)的位置上施加一个 Rx 旋转门， 角度为 pi
which_qubit = 0
cir.ry(theta, which_qubit)
# 打印出这个量子门
# 转换成 numpy 
print('量子门的矩阵表达式为：')
print(cir.U.numpy())

量子门的矩阵表达式为：
[[ 6.123234e-17+0.j -1.000000e+00+0.j]
 [ 1.000000e+00+0.j  6.123234e-17+0.j]]
/usr/local/anaconda3/envs/paddle_quantum_env/lib/python3.7/site-packages/paddle/fluid/framework.py:687: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  elif dtype == np.bool:
/usr/local/anaconda3/envs/paddle_quantum_env/lib/python3.7/site-packages/paddle/tensor/creation.py:143: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  

In [5]:
import numpy as np
c = np.array([1,2,3])
print(c)
theta = np.array([np.pi])
print(theta)

[1 2 3]
[3.14159265]
/usr/local/anaconda3/envs/paddle_quantum_env/lib/python3.7/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [18]:
import numpy as np
import paddle
from paddle_quantum.circuit import UAnsatz

# 设置角度参数 theta 
theta = np.full([4], np.pi)
    
# 我们需要将 Numpy array 转换成 Paddle 中的 Tensor
theta = paddle.to_tensor(theta)

# 初始化量子电路
num_qubits = 2
cir = UAnsatz(num_qubits)
print('origin:',cir.U.numpy())
# 添加单比特旋转门
cir.ry(theta[0], 0)
print('ro',cir.U.numpy().real)
cir.ry(theta[1], 1)
print('r1',cir.U.numpy().real)
# 添加两比特门
cir.cnot([0, 1])
print('cn',cir.U.numpy().real)
# 添加单比特旋转门
cir.ry(theta[2], 0)
print('ro',cir.U.numpy().real)
cir.ry(theta[3], 1)
print('r1',cir.U.numpy().real)
print('图中量子神经网络 U(theta=pi) 的矩阵表达式是:')
print(cir.U.numpy().real)

origin: [[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]]
ro [[ 6.123234e-17  0.000000e+00 -1.000000e+00  0.000000e+00]
 [ 0.000000e+00  6.123234e-17  0.000000e+00 -1.000000e+00]
 [ 1.000000e+00  0.000000e+00  6.123234e-17  0.000000e+00]
 [ 0.000000e+00  1.000000e+00  0.000000e+00  6.123234e-17]]
r1 [[ 3.74939946e-33 -6.12323400e-17 -6.12323400e-17  1.00000000e+00]
 [ 6.12323400e-17  3.74939946e-33 -1.00000000e+00 -6.12323400e-17]
 [ 6.12323400e-17 -1.00000000e+00  3.74939946e-33 -6.12323400e-17]
 [ 1.00000000e+00  6.12323400e-17  6.12323400e-17  3.74939946e-33]]
cn [[ 3.74939946e-33 -6.12323400e-17 -6.12323400e-17  1.00000000e+00]
 [ 6.12323400e-17  3.74939946e-33 -1.00000000e+00 -6.12323400e-17]
 [ 1.00000000e+00  6.12323400e-17  6.12323400e-17  3.74939946e-33]
 [ 6.12323400e-17 -1.00000000e+00  3.74939946e-33 -6.12323400e-17]]
ro [[-1.000000e+00 -6.123234e-17 -6.123234e-17  6.123234e-17]
 [-6.123234e-17  1.00

In [ ]:
def psi_norm(weights):
    """return normalization <psi|psi>, where |psi> = A|x>"""

In [ ]:
def cost_loc(weights):
    """Local cost function"""
    pass